### ISSUE TITLE
Shell script not necessary.

### ISSUE THREAD

**Issue by janderholm** [maveonair/helix-ppa#1]
I don't think the helix.sh script is necessary.

The hx binary will look for a runtime directory in the same directory it is placed it. I.e:

_/usr/lib/helix/hx_ will look for a runtime in _/usr/lib/helix/runtime_. So a simple symlink should suffice. 

I realize it's not the end of the world, but every process call counts!

**Comment by maveonair** [comment]
Thank you very much for this hint. Do you have any idea why other distributions have it packaged this way? I ask because I am inspired by others like Archlinux: https://github.com/archlinux/svntogit-community/tree/packages/helix/trunk

**Comment by maveonair** [comment]
Thanks for reporting but I will close it for now.
