### ISSUE TITLE
Completion scripts installed under wrong names

### ISSUE THREAD

**Issue by tranzystorekk** [maveonair/helix-ppa#11]
Noticed completions are installed under the `helix` name instead of `hx`, which prevents them from working (as reported on helix matrix chat).

**Comment by jrvidal** [comment]
Also, it looks like the folder for zsh completions might not be correct. In a vanilla Ubuntu installation, `echo $fpath` shows:

```console
/usr/local/share/zsh/site-functions
/usr/share/zsh/vendor-functions
/usr/share/zsh/vendor-completions
/usr/share/zsh/functions/Calendar
# etc.
```
