### ISSUE TITLE
Debian packages

### ISSUE THREAD

**Issue by jonas-w** [maveonair/helix-ppa#2]
If I see this correctly this only works on Ubuntu, would it be possible to make debian available?

**Comment by maveonair** [comment]
I am not planning to create a specific debian repository. But you could try to download the deb file from PPA here https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor/+packages

**Comment by jonas-w** [comment]
Yeah I already tried that, doesn't work. Maybe you should change your description and readme from debian to ubuntu, as Debian doesn't work.

**Comment by maveonair** [comment]
Thanks for the suggestion, I have done that.
