### ISSUE TITLE
Is it possible to add packages for armhf (Raspberry Pi <= 3)?

### ISSUE THREAD

**Issue by tanuva** [maveonair/helix-ppa#3]
G'day,

I tried to install helix on my RPi running Raspbian Bullseye. Alas, it requires packages for armhf instead of arm64:
```
dpkg: error processing archive helix_23.03-3~ubuntu20.04~ppa1_arm64.deb (--install):
 package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
 helix_23.03-3~ubuntu20.04~ppa1_arm64.deb
```

I admit I have no idea how you manage a PPA - is it possible to "just enable" building packages for armhf, too? That would be awesome. :)

**Comment by maveonair** [comment]
In issue https://github.com/maveonair/helix-ppa/issues/2 it was stated that the existing packages not running on Debian. Therefore, I doubt that it will work for armhf on Raspian too. Do you have any change to validate if the arm64 package works on Raspian?

**Comment by tanuva** [comment]
Alas they didn't say what exactly wasn't working on Debian in the other issue. Assuming you meant "chance" instead of "change", I extracted the arm64 package manually and tried to run the executable on an RPi 3:
```
$ HELIX_RUNTIME=var/lib/helix/runtime ./usr/lib/helix/hx
-bash: ./usr/lib/helix/hx: cannot execute binary file: Exec format error
```
...and well, the architectures don't match. So dedicated armhf packages seem to be needed. I don't know about further pitfalls in Ubuntu vs. Debian though.

If building for armhf isn't straightforward for you, I could maybe try using the package sources to build on my Pi. The last time I read up on packaging for Debian that seemed to be a lot more complex than Arch... 😅

**Update**: Meanwhile I realized that I was in fact trying a Raspberry Pi 3 which has armhf architecture. Sorry about that. On my actual RPi **4**, the existing arm64 package works (as in: I can start helix. Haven't tried more yet.) That's the package for Ubuntu focal installed on Raspbian 11 (bullseye).

I tried building an armhf package myself on the Pi 3 now. After compiling for 102 minutes it failed because of missing `dch`. I shall install `devscripts` and do another run.

**Comment by tanuva** [comment]
Okay, so I ended up patching the build script a bit to improve iteration times and patching helix' `Cargo.toml` minimally to parse successfully. In the end, the fakeroot environment appears to use the system cargo instead of the rustup installation in my home. Therefore it ends up noticing that cargo is too old:
```
dpkg-buildpackage -us -uc -ui -S -sa
dpkg-buildpackage: info: source package helix
dpkg-buildpackage: info: source version 23.03-3~debian~ppa2
dpkg-buildpackage: info: source distribution bullseye
dpkg-buildpackage: info: source changed by Marcel Kummer <email redacted>
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/pi/code/helix-ppa/target/helix-23.03'
cargo clean
error: failed to parse manifest at `/home/pi/code/helix-ppa/target/helix-23.03/helix-core/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
make[1]: *** [debian/rules:7: override_dh_auto_clean] Error 101
make[1]: Leaving directory '/home/pi/code/helix-ppa/target/helix-23.03'
make: *** [debian/rules:4: clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
```

...and at this point I'm out of ideas for building on the Pi. It seems like it would generally run on Debian bullseye (see the arm64 Pi 4). However compiling it with the cargo/rust shipped in bullseye seems not to be possible.

**Comment by maveonair** [comment]
On a RPI 3 you can install the 64bit (arm64) version of PiOS, Ubuntu, etc. too. Maybe you can try that instead?

**Comment by tanuva** [comment]
Oh. Interesting point, I wonder why I ended up with armhf in the first place. (Maybe arm64 Raspbian didn't exist yet? That Pi has been running for a while now...)
I'm probably not going to set the Pi up anew anytime soon, but that sounds like *the workaround* then. :)
