### ISSUE TITLE
sudo add-apt-repository ppa:maveonair/helix-editor the package can be found

### ISSUE THREAD

**Issue by goodhubcn** [maveonair/helix-ppa#5]
$ sudo add-apt-repository ppa:maveonair/helix-editor
Repository: 'deb https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu/ jammy main'
Description:
A post-modern text editor.

The source code used to build the package can be found here: https://github.com/maveonair/helix-ppa.

Please report packaging issues to https://github.com/maveonair/helix-ppa/issues
More info: https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.

**Comment by goodhubcn** [comment]
How to fix?

**Comment by Lucksinia** [comment]
Press enter? as it asks you to do?

**Comment by maveonair** [comment]
Yes, press enter to enable the repository and then install Helix with

```
sudo apt install helix
```
