### ISSUE TITLE
Unconventional use of /var/lib/

### ISSUE THREAD

**Issue by BCMM** [maveonair/helix-ppa#8]
Typically, /var/lib/ would contain data that is expected to be changed by an application at runtime, rather than data that is updated only through the package manager. Wouldn't /usr/lib/helix/ be a more standard location for the files that are currently installed in /var/lib/helix/?

In addition to matching what other packages seem to do, I note that this configuration [is used in an example in upstream docs](https://docs.helix-editor.com/install.html#note-to-packagers).

**Comment by stappersg** [comment]
Feedback on merge request #10, Set default runtime to /usr/lib/helix/runtime, will probably move this issue forward.
